### ISSUE TITLE
[Feature Request] Exclude routes page

### ISSUE THREAD

**Issue by alvinindra** [jbaubree/vite-plugin-pages-sitemap#154]
Is there possible to customize robots disallow the routes page from the vite-plugin-pages?

And I have problem when generate dynamic routes from api there such an error too.
```
[vite-plugin-pages] Could not load /@vite-plugin-pages/generated-pages?id=virtual:generated-pages (imported by src/main.js): products.map is not a function
error during build:
TypeError: Could not load /@vite-plugin-pages/generated-pages?id=virtual:generated-pages (imported by src/main.js): products.map is not a function
    at Object.onRoutesGenerated (file:///D:/Project/Web%20Brand/web-brand/vite.config.js.timestamp-1664157424389.mjs:36:40)     
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async computeVueRoutes (file:///D:/Project/Web%20Brand/web-brrand/node_modules/.pnpm/vite-plugin-pages@0.25.0_vite@3.1.3/node_moudules/vite-plugin-pages/dist/index.mjs:514:17)
    at async resolveVueRoutes (file:///D:/Project/Web%20Brand/web-brrand/node_modules/.pnpm/vite-plugin-pages@0.25.0_vite@3.1.3/node_moudules/vite-plugin-pages/dist/index.mjs:519:23)
    at async file:///D:/Project/Web%20Brand/web-brand/node_modules/..pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:221113:98
    at async Queue.work (file:///D:/Project/Web%20Brand/web-brand/noode_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/orollup.js:22820:32)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by jbaubree** [comment]
Hi, thanks for reporting, you can now try `v1.4.0`. This version can get excludes[] with array of paths. You have a working example in example folder. Feel free to close this issue if this has fixed your issue
